title: 杨慧鑫的作品集
description: 广告艺术指导 | 视觉创意
baseurl: ""
url: ""
markdown: kramdown

# 资源路径设置
sass:
  style: compressed
  
# 静态文件设置
defaults:
  - scope:
      path: "assets"
    values:
      image: true
  - scope:
      path: "images"
    values:
      image: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 作品集设置
collections:
  works:
    output: true
    permalink: /:collection/:name/

excerpt_separator: "##"

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 关于我
    url: /about/

# 社交媒体链接
social:
  email: mojimo.cc@gmail.com
  phone: （+86）15800440416
